services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres_user
      POSTGRES_DB: postgres_db
    volumes: 
      - postgres_db_data:/var/lib/postgres/data

  backend: 
    image: BackEnd
    restart: always
    volumes: 
      - backend_data:
volumes: 
  postgres_db_data:
  backend_data: